#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="RDE_DyM"

cp -r 0.org 0
cp -r 0.org ./internal/0

cp ./system/controlDict_1 ./system/controlDict
runApplication $application
rm log*
cp -r 172800 ./internal/

cp ./system/mapFieldsDict_1 ./system/mapFieldsDict
mapFields ./new_bc_1/

cp ./system/mapFieldsDict_2 ./system/mapFieldsDict
mapFields ./internal/

cp ./system/controlDict_2 ./system/controlDict
runApplication $application
rm log*
cp -r 345600 ./internal/

cp ./system/mapFieldsDict_1 ./system/mapFieldsDict
mapFields ./new_bc_2/

cp ./system/mapFieldsDict_2 ./system/mapFieldsDict
mapFields ./internal/

cp ./system/controlDict_3 ./system/controlDict
runApplication $application
rm log*
cp -r 518400 ./internal/



